In [90]:
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

# Creating Labels and Features

In [91]:
#Read the clean data into a pandas df to build the model
path = Path("resources\\clean_data\\fraud_clean_data.csv")
model_df = pd.read_csv(path)
model_df.head(10)


early morning (1-6), late morning(6-12), afternoon(12-4), evening(4-8), night(8-12)

,transaction_id,time,category,amount,age,gender,state,city_pop,is_fraud
0,119106,07:55:28,shopping_pos,1.07,59.0,F,CT,5438,0
1,179292,14:05:16,kids_pets,94.99,41.0,M,OK,7163,0
2,540729,16:22:29,kids_pets,31.28,69.0,F,MO,602,0
3,374360,10:44:50,gas_transport,73.06,41.0,M,OK,7163,0
4,314574,01:50:09,misc_net,9.99,52.0,F,IA,2036,0
5,377296,17:04:04,personal_care,28.50,52.0,M,TX,248858,0
6,399943,22:26:16,shopping_pos,9.09,32.0,F,NY,69,0
7,1481,20:46:20,health_fitness,1.64,62.0,M,MD,626,0
8,465665,10:15:23,gas_transport,55.90,45.0,F,TX,1563,0
9,430957,16:31:41,kids_pets,50.61,51.0,F,CA,54287,0

In [92]:
#Drop the transaction_id since it's not a feature for the model
model_df.drop(columns='transaction_id', inplace=True)
model_df

            time       category  amount   age gender state  city_pop  is_fraud
0       07:55:28   shopping_pos    1.07  59.0      F    CT      5438         0
1       14:05:16      kids_pets   94.99  41.0      M    OK      7163         0
2       16:22:29      kids_pets   31.28  69.0      F    MO       602         0
3       10:44:50  gas_transport   73.06  41.0      M    OK      7163         0
4       01:50:09       misc_net    9.99  52.0      F    IA      2036         0
...          ...            ...     ...   ...    ...   ...       ...       ...
111139  12:42:49    food_dining    8.22  24.0      F    IA      1583         0
111140  21:29:49  personal_care  205.69  35.0      F    OH      7646         0
111141  01:05:31       misc_net  277.63  42.0      M    MA     47249         0
111142  04:16:28   shopping_net   13.29  92.0      F    KY       571         0
111143  23:38:46    food_dining  100.46  39.0      M    WI      1360         1

[111144 rows x 8 columns]

In [93]:
#Separate the labels and the features 

#y values are the lables
y = model_df['is_fraud']

#X values are the features (everything in the dataframe except the labels)
X = model_df.drop(columns=['is_fraud'])

In [94]:
#Review the series of lables
y.head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: is_fraud, dtype: int64

In [95]:
#Review the features dataframe
X.head()

       time       category  amount   age gender state  city_pop
0  07:55:28   shopping_pos    1.07  59.0      F    CT      5438
1  14:05:16      kids_pets   94.99  41.0      M    OK      7163
2  16:22:29      kids_pets   31.28  69.0      F    MO       602
3  10:44:50  gas_transport   73.06  41.0      M    OK      7163
4  01:50:09       misc_net    9.99  52.0      F    IA      2036

In [96]:
#Check the balance of the lables and features
y.value_counts()

0    110718
1       426
Name: is_fraud, dtype: int64

# Split the Data

In [97]:
#Split the data into training and testing sets. Random state of 1 will be assigned.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# Create the Logistic Regression

In [98]:
#Use the LogisticRegression function and assign it to a variable
#Random state will be 1 since we used it earlier
classifier = LogisticRegression(random_state=1)
classifier

#Fit the model with the classifier
classifier.fit(X_train, y_train)

ValueError: could not convert string to float: '17:24:10'