In [193]:
#Import dependencies
import numpy as np
import pandas as pd
from pathlib import Path
from datetime import datetime

# Data Export and Cleaning

In [194]:
#Read in the csv file to Pandas dataframe
path = Path('resources\\raw_data\\fraud_data.csv')
fraud_df = pd.read_csv(path)
fraud_df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,119106,2020-08-02 07:55:28,377895991033232,"fraud_Bahringer, Schoen and Corkery",shopping_pos,1.07,Kimberly,Myers,F,6881 King Isle Suite 228,...,41.4682,-72.5751,5438,"Librarian, academic",1964-11-17,cf581d75ccc9ba838a05dec8bfa78b5b,1375430128,41.240083,-71.837788,0
1,179292,2020-08-23 14:05:16,30364087349027,"fraud_Romaguera, Wehner and Tromp",kids_pets,94.99,Samuel,Sandoval,M,0005 Morrison Land,...,35.8896,-96.0887,7163,Fitness centre manager,1982-02-05,b1bfaf13224da41f422db483fd810dd7,1377266716,35.156537,-95.806648,0
2,540729,2020-12-28 16:22:29,30328384440870,fraud_Berge-Hills,kids_pets,31.28,Helen,Campbell,F,182 Sergio Summit Apt. 129,...,40.0290,-93.1607,602,Cytogeneticist,1954-07-14,cde9fc0136873645778d0ad8817db655,1388247749,39.888665,-93.106804,0
3,374360,2020-11-14 10:44:50,30364087349027,"fraud_Connelly, Reichert and Fritsch",gas_transport,73.06,Samuel,Sandoval,M,0005 Morrison Land,...,35.8896,-96.0887,7163,Fitness centre manager,1982-02-05,90b8429191e5c83df1afba4e5db4d61e,1384425890,36.734101,-96.737345,0
4,314574,2020-10-19 01:50:09,4198470814557,fraud_Kuphal-Predovic,misc_net,9.99,Christie,Williamson,F,519 Jerry Views,...,41.4768,-95.3509,2036,Engineering geologist,1971-08-20,e4893795b6b3e41667129b9ed13b9650,1382147409,40.922072,-94.899388,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111139,444284,2020-12-07 12:42:49,4839043708100390,"fraud_Bahringer, Osinski and Block",food_dining,8.22,Meredith,Campbell,F,043 Hanson Turnpike,...,41.1826,-92.3097,1583,Geochemist,1999-06-28,9d0a293688b043f0952ceb3250fd7255,1386420169,41.496857,-91.453971,0
111140,89444,2020-07-21 21:29:49,6011367958204270,fraud_Friesen-Ortiz,personal_care,205.69,Tammy,Ayers,F,1652 James Mews,...,41.2419,-81.7453,7646,Medical sales representative,1988-09-15,f6784d73b8dbb4d39479bd02d210fa5b,1374442189,41.813370,-81.627877,0
111141,298536,2020-10-12 01:05:31,4469777115158234880,fraud_Ruecker Group,misc_net,277.63,Gregory,Graham,M,4005 Dana Glens,...,42.7280,-71.1810,47249,Market researcher,1980-11-22,c76225c92adac33abe5e9dd6606f04b3,1381539931,42.779729,-70.896452,0
111142,301993,2020-10-13 04:16:28,4066595222529,"fraud_Schmeler, Bashirian and Price",shopping_net,13.29,Jamie,Olson,F,3423 Michael Canyon Suite 276,...,37.8795,-82.7251,571,Quarry manager,1931-03-07,bed944f645238f76c9664729c0f8f923,1381637788,37.449586,-82.853977,0
111143,354010,2020-11-04 23:38:46,2229378226512508,fraud_O'Hara-Wilderman,food_dining,100.46,Thomas,Hale,M,949 Smith Parkway,...,43.4987,-90.2796,1360,Occupational hygienist,1984-11-06,6b4fe7b7c411e2c3190e9e53af0819cf,1383608326,44.490630,-89.744465,1

In [195]:
#Get a list of the columns
fraud_df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [196]:
#Rename 'Unamed: 0' to 'transaction id'
fraud_df.rename(columns={'Unnamed: 0' : 'transaction id'}, inplace=True)
fraud_df

,transaction id,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,119106,2020-08-02 07:55:28,377895991033232,"fraud_Bahringer, Schoen and Corkery",shopping_pos,1.07,Kimberly,Myers,F,6881 King Isle Suite 228,...,41.4682,-72.5751,5438,"Librarian, academic",1964-11-17,cf581d75ccc9ba838a05dec8bfa78b5b,1375430128,41.240083,-71.837788,0
1,179292,2020-08-23 14:05:16,30364087349027,"fraud_Romaguera, Wehner and Tromp",kids_pets,94.99,Samuel,Sandoval,M,0005 Morrison Land,...,35.8896,-96.0887,7163,Fitness centre manager,1982-02-05,b1bfaf13224da41f422db483fd810dd7,1377266716,35.156537,-95.806648,0
2,540729,2020-12-28 16:22:29,30328384440870,fraud_Berge-Hills,kids_pets,31.28,Helen,Campbell,F,182 Sergio Summit Apt. 129,...,40.0290,-93.1607,602,Cytogeneticist,1954-07-14,cde9fc0136873645778d0ad8817db655,1388247749,39.888665,-93.106804,0
3,374360,2020-11-14 10:44:50,30364087349027,"fraud_Connelly, Reichert and Fritsch",gas_transport,73.06,Samuel,Sandoval,M,0005 Morrison Land,...,35.8896,-96.0887,7163,Fitness centre manager,1982-02-05,90b8429191e5c83df1afba4e5db4d61e,1384425890,36.734101,-96.737345,0
4,314574,2020-10-19 01:50:09,4198470814557,fraud_Kuphal-Predovic,misc_net,9.99,Christie,Williamson,F,519 Jerry Views,...,41.4768,-95.3509,2036,Engineering geologist,1971-08-20,e4893795b6b3e41667129b9ed13b9650,1382147409,40.922072,-94.899388,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111139,444284,2020-12-07 12:42:49,4839043708100390,"fraud_Bahringer, Osinski and Block",food_dining,8.22,Meredith,Campbell,F,043 Hanson Turnpike,...,41.1826,-92.3097,1583,Geochemist,1999-06-28,9d0a293688b043f0952ceb3250fd7255,1386420169,41.496857,-91.453971,0
111140,89444,2020-07-21 21:29:49,6011367958204270,fraud_Friesen-Ortiz,personal_care,205.69,Tammy,Ayers,F,1652 James Mews,...,41.2419,-81.7453,7646,Medical sales representative,1988-09-15,f6784d73b8dbb4d39479bd02d210fa5b,1374442189,41.813370,-81.627877,0
111141,298536,2020-10-12 01:05:31,4469777115158234880,fraud_Ruecker Group,misc_net,277.63,Gregory,Graham,M,4005 Dana Glens,...,42.7280,-71.1810,47249,Market researcher,1980-11-22,c76225c92adac33abe5e9dd6606f04b3,1381539931,42.779729,-70.896452,0
111142,301993,2020-10-13 04:16:28,4066595222529,"fraud_Schmeler, Bashirian and Price",shopping_net,13.29,Jamie,Olson,F,3423 Michael Canyon Suite 276,...,37.8795,-82.7251,571,Quarry manager,1931-03-07,bed944f645238f76c9664729c0f8f923,1381637788,37.449586,-82.853977,0
111143,354010,2020-11-04 23:38:46,2229378226512508,fraud_O'Hara-Wilderman,food_dining,100.46,Thomas,Hale,M,949 Smith Parkway,...,43.4987,-90.2796,1360,Occupational hygienist,1984-11-06,6b4fe7b7c411e2c3190e9e53af0819cf,1383608326,44.490630,-89.744465,1

In [197]:
#Rename amt to amount
fraud_df.rename(columns={'amt' : 'amount'}, inplace=True)
fraud_df

,transaction id,trans_date_trans_time,cc_num,merchant,category,amount,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,119106,2020-08-02 07:55:28,377895991033232,"fraud_Bahringer, Schoen and Corkery",shopping_pos,1.07,Kimberly,Myers,F,6881 King Isle Suite 228,...,41.4682,-72.5751,5438,"Librarian, academic",1964-11-17,cf581d75ccc9ba838a05dec8bfa78b5b,1375430128,41.240083,-71.837788,0
1,179292,2020-08-23 14:05:16,30364087349027,"fraud_Romaguera, Wehner and Tromp",kids_pets,94.99,Samuel,Sandoval,M,0005 Morrison Land,...,35.8896,-96.0887,7163,Fitness centre manager,1982-02-05,b1bfaf13224da41f422db483fd810dd7,1377266716,35.156537,-95.806648,0
2,540729,2020-12-28 16:22:29,30328384440870,fraud_Berge-Hills,kids_pets,31.28,Helen,Campbell,F,182 Sergio Summit Apt. 129,...,40.0290,-93.1607,602,Cytogeneticist,1954-07-14,cde9fc0136873645778d0ad8817db655,1388247749,39.888665,-93.106804,0
3,374360,2020-11-14 10:44:50,30364087349027,"fraud_Connelly, Reichert and Fritsch",gas_transport,73.06,Samuel,Sandoval,M,0005 Morrison Land,...,35.8896,-96.0887,7163,Fitness centre manager,1982-02-05,90b8429191e5c83df1afba4e5db4d61e,1384425890,36.734101,-96.737345,0
4,314574,2020-10-19 01:50:09,4198470814557,fraud_Kuphal-Predovic,misc_net,9.99,Christie,Williamson,F,519 Jerry Views,...,41.4768,-95.3509,2036,Engineering geologist,1971-08-20,e4893795b6b3e41667129b9ed13b9650,1382147409,40.922072,-94.899388,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111139,444284,2020-12-07 12:42:49,4839043708100390,"fraud_Bahringer, Osinski and Block",food_dining,8.22,Meredith,Campbell,F,043 Hanson Turnpike,...,41.1826,-92.3097,1583,Geochemist,1999-06-28,9d0a293688b043f0952ceb3250fd7255,1386420169,41.496857,-91.453971,0
111140,89444,2020-07-21 21:29:49,6011367958204270,fraud_Friesen-Ortiz,personal_care,205.69,Tammy,Ayers,F,1652 James Mews,...,41.2419,-81.7453,7646,Medical sales representative,1988-09-15,f6784d73b8dbb4d39479bd02d210fa5b,1374442189,41.813370,-81.627877,0
111141,298536,2020-10-12 01:05:31,4469777115158234880,fraud_Ruecker Group,misc_net,277.63,Gregory,Graham,M,4005 Dana Glens,...,42.7280,-71.1810,47249,Market researcher,1980-11-22,c76225c92adac33abe5e9dd6606f04b3,1381539931,42.779729,-70.896452,0
111142,301993,2020-10-13 04:16:28,4066595222529,"fraud_Schmeler, Bashirian and Price",shopping_net,13.29,Jamie,Olson,F,3423 Michael Canyon Suite 276,...,37.8795,-82.7251,571,Quarry manager,1931-03-07,bed944f645238f76c9664729c0f8f923,1381637788,37.449586,-82.853977,0
111143,354010,2020-11-04 23:38:46,2229378226512508,fraud_O'Hara-Wilderman,food_dining,100.46,Thomas,Hale,M,949 Smith Parkway,...,43.4987,-90.2796,1360,Occupational hygienist,1984-11-06,6b4fe7b7c411e2c3190e9e53af0819cf,1383608326,44.490630,-89.744465,1

In [198]:
#Convert the date and time in the column 'trans_date_trans_time'
fraud_df['trans_date_trans_time'] = pd.to_datetime(fraud_df['trans_date_trans_time'])

#Split the 'trans_date_trans_time' column into two columns: date and time
fraud_df['date'] = fraud_df['trans_date_trans_time'].dt.date
fraud_df['time'] = fraud_df['trans_date_trans_time'].dt.time
fraud_df

,transaction id,trans_date_trans_time,cc_num,merchant,category,amount,first,last,gender,street,...,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,date,time
0,119106,2020-08-02 07:55:28,377895991033232,"fraud_Bahringer, Schoen and Corkery",shopping_pos,1.07,Kimberly,Myers,F,6881 King Isle Suite 228,...,5438,"Librarian, academic",1964-11-17,cf581d75ccc9ba838a05dec8bfa78b5b,1375430128,41.240083,-71.837788,0,2020-08-02,07:55:28
1,179292,2020-08-23 14:05:16,30364087349027,"fraud_Romaguera, Wehner and Tromp",kids_pets,94.99,Samuel,Sandoval,M,0005 Morrison Land,...,7163,Fitness centre manager,1982-02-05,b1bfaf13224da41f422db483fd810dd7,1377266716,35.156537,-95.806648,0,2020-08-23,14:05:16
2,540729,2020-12-28 16:22:29,30328384440870,fraud_Berge-Hills,kids_pets,31.28,Helen,Campbell,F,182 Sergio Summit Apt. 129,...,602,Cytogeneticist,1954-07-14,cde9fc0136873645778d0ad8817db655,1388247749,39.888665,-93.106804,0,2020-12-28,16:22:29
3,374360,2020-11-14 10:44:50,30364087349027,"fraud_Connelly, Reichert and Fritsch",gas_transport,73.06,Samuel,Sandoval,M,0005 Morrison Land,...,7163,Fitness centre manager,1982-02-05,90b8429191e5c83df1afba4e5db4d61e,1384425890,36.734101,-96.737345,0,2020-11-14,10:44:50
4,314574,2020-10-19 01:50:09,4198470814557,fraud_Kuphal-Predovic,misc_net,9.99,Christie,Williamson,F,519 Jerry Views,...,2036,Engineering geologist,1971-08-20,e4893795b6b3e41667129b9ed13b9650,1382147409,40.922072,-94.899388,0,2020-10-19,01:50:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111139,444284,2020-12-07 12:42:49,4839043708100390,"fraud_Bahringer, Osinski and Block",food_dining,8.22,Meredith,Campbell,F,043 Hanson Turnpike,...,1583,Geochemist,1999-06-28,9d0a293688b043f0952ceb3250fd7255,1386420169,41.496857,-91.453971,0,2020-12-07,12:42:49
111140,89444,2020-07-21 21:29:49,6011367958204270,fraud_Friesen-Ortiz,personal_care,205.69,Tammy,Ayers,F,1652 James Mews,...,7646,Medical sales representative,1988-09-15,f6784d73b8dbb4d39479bd02d210fa5b,1374442189,41.813370,-81.627877,0,2020-07-21,21:29:49
111141,298536,2020-10-12 01:05:31,4469777115158234880,fraud_Ruecker Group,misc_net,277.63,Gregory,Graham,M,4005 Dana Glens,...,47249,Market researcher,1980-11-22,c76225c92adac33abe5e9dd6606f04b3,1381539931,42.779729,-70.896452,0,2020-10-12,01:05:31
111142,301993,2020-10-13 04:16:28,4066595222529,"fraud_Schmeler, Bashirian and Price",shopping_net,13.29,Jamie,Olson,F,3423 Michael Canyon Suite 276,...,571,Quarry manager,1931-03-07,bed944f645238f76c9664729c0f8f923,1381637788,37.449586,-82.853977,0,2020-10-13,04:16:28
111143,354010,2020-11-04 23:38:46,2229378226512508,fraud_O'Hara-Wilderman,food_dining,100.46,Thomas,Hale,M,949 Smith Parkway,...,1360,Occupational hygienist,1984-11-06,6b4fe7b7c411e2c3190e9e53af0819cf,1383608326,44.490630,-89.744465,1,2020-11-04,23:38:46

In [199]:
#Drop the 'trans_date_trans_time' since it's been split into separate date and time columns
fraud_df.drop(columns='trans_date_trans_time', inplace=True)

In [200]:
#In order to convert the date of birth into age, we need the following code:

#Convert the date of birth column ('dob') to a datetime object 
fraud_df['dob'] = pd.to_datetime(fraud_df['dob'])

#Get the current date and time with the datetime.now() function
current_date = datetime.now()

#Make a new column in our dataframe named 'age' that will subtract our current date and the dob
#"astype('<m8[Y]')" simply means to convert the date change (current date - date of birth, in this case) to a NumPy object
fraud_df['age'] = (current_date - fraud_df['dob']).astype('<m8[Y]')

#Drop the 'dob' column
fraud_df.drop(columns='dob', inplace=True)


fraud_df

,transaction id,cc_num,merchant,category,amount,first,last,gender,street,city,...,city_pop,job,trans_num,unix_time,merch_lat,merch_long,is_fraud,date,time,age
0,119106,377895991033232,"fraud_Bahringer, Schoen and Corkery",shopping_pos,1.07,Kimberly,Myers,F,6881 King Isle Suite 228,Higganum,...,5438,"Librarian, academic",cf581d75ccc9ba838a05dec8bfa78b5b,1375430128,41.240083,-71.837788,0,2020-08-02,07:55:28,59.0
1,179292,30364087349027,"fraud_Romaguera, Wehner and Tromp",kids_pets,94.99,Samuel,Sandoval,M,0005 Morrison Land,Mounds,...,7163,Fitness centre manager,b1bfaf13224da41f422db483fd810dd7,1377266716,35.156537,-95.806648,0,2020-08-23,14:05:16,41.0
2,540729,30328384440870,fraud_Berge-Hills,kids_pets,31.28,Helen,Campbell,F,182 Sergio Summit Apt. 129,Browning,...,602,Cytogeneticist,cde9fc0136873645778d0ad8817db655,1388247749,39.888665,-93.106804,0,2020-12-28,16:22:29,69.0
3,374360,30364087349027,"fraud_Connelly, Reichert and Fritsch",gas_transport,73.06,Samuel,Sandoval,M,0005 Morrison Land,Mounds,...,7163,Fitness centre manager,90b8429191e5c83df1afba4e5db4d61e,1384425890,36.734101,-96.737345,0,2020-11-14,10:44:50,41.0
4,314574,4198470814557,fraud_Kuphal-Predovic,misc_net,9.99,Christie,Williamson,F,519 Jerry Views,Avoca,...,2036,Engineering geologist,e4893795b6b3e41667129b9ed13b9650,1382147409,40.922072,-94.899388,0,2020-10-19,01:50:09,52.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111139,444284,4839043708100390,"fraud_Bahringer, Osinski and Block",food_dining,8.22,Meredith,Campbell,F,043 Hanson Turnpike,Hedrick,...,1583,Geochemist,9d0a293688b043f0952ceb3250fd7255,1386420169,41.496857,-91.453971,0,2020-12-07,12:42:49,24.0
111140,89444,6011367958204270,fraud_Friesen-Ortiz,personal_care,205.69,Tammy,Ayers,F,1652 James Mews,Hinckley,...,7646,Medical sales representative,f6784d73b8dbb4d39479bd02d210fa5b,1374442189,41.813370,-81.627877,0,2020-07-21,21:29:49,35.0
111141,298536,4469777115158234880,fraud_Ruecker Group,misc_net,277.63,Gregory,Graham,M,4005 Dana Glens,Methuen,...,47249,Market researcher,c76225c92adac33abe5e9dd6606f04b3,1381539931,42.779729,-70.896452,0,2020-10-12,01:05:31,42.0
111142,301993,4066595222529,"fraud_Schmeler, Bashirian and Price",shopping_net,13.29,Jamie,Olson,F,3423 Michael Canyon Suite 276,River,...,571,Quarry manager,bed944f645238f76c9664729c0f8f923,1381637788,37.449586,-82.853977,0,2020-10-13,04:16:28,92.0
111143,354010,2229378226512508,fraud_O'Hara-Wilderman,food_dining,100.46,Thomas,Hale,M,949 Smith Parkway,Cazenovia,...,1360,Occupational hygienist,6b4fe7b7c411e2c3190e9e53af0819cf,1383608326,44.490630,-89.744465,1,2020-11-04,23:38:46,39.0

In [201]:
#Get the columns for reordering
fraud_df.columns

Index(['transaction id', 'cc_num', 'merchant', 'category', 'amount', 'first',
       'last', 'gender', 'street', 'city', 'state', 'zip', 'lat', 'long',
       'city_pop', 'job', 'trans_num', 'unix_time', 'merch_lat', 'merch_long',
       'is_fraud', 'date', 'time', 'age'],
      dtype='object')

In [202]:
#Reorder the columns
fraud_df = fraud_df[['transaction id', 'date', 'time', 'cc_num', 'merchant', 'category', 'amount', 'first',
       'last', 'age', 'gender', 'street', 'city', 'state', 'zip', 'lat', 'long',
       'city_pop', 'job', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud']]

In [203]:
#Drop the columns that are not features of the model
fraud_df.drop(columns=['trans_num', 'cc_num', 'first', 'last', 'zip', 'merch_lat', 'merch_long', 'street', 
                       'unix_time', 'merchant', 'job', 'city', 'date', 'lat', 'long'], inplace=True)
fraud_df

C:\Users\Asher\AppData\Local\Temp\ipykernel_14268\583440135.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fraud_df.drop(columns=['trans_num', 'cc_num', 'first', 'last', 'zip', 'merch_lat', 'merch_long', 'street',

,transaction id,time,category,amount,age,gender,state,city_pop,is_fraud
0,119106,07:55:28,shopping_pos,1.07,59.0,F,CT,5438,0
1,179292,14:05:16,kids_pets,94.99,41.0,M,OK,7163,0
2,540729,16:22:29,kids_pets,31.28,69.0,F,MO,602,0
3,374360,10:44:50,gas_transport,73.06,41.0,M,OK,7163,0
4,314574,01:50:09,misc_net,9.99,52.0,F,IA,2036,0
...,...,...,...,...,...,...,...,...,...
111139,444284,12:42:49,food_dining,8.22,24.0,F,IA,1583,0
111140,89444,21:29:49,personal_care,205.69,35.0,F,OH,7646,0
111141,298536,01:05:31,misc_net,277.63,42.0,M,MA,47249,0
111142,301993,04:16:28,shopping_net,13.29,92.0,F,KY,571,0
111143,354010,23:38:46,food_dining,100.46,39.0,M,WI,1360,1

In [204]:
#Export the clean data to a separate folder
fraud_df.to_csv('resources\\clean_data\\fraud_clean_data.csv', index=False)

# SQLAlchemy Export

Below is the export of the 'fraud_df' in Pandas to the 'FraudDetection' SQL database for this project. This will automatically create a new table 'fraud_data' if it does not already exist. 

When creating the engine, Replace 'PASSWORD' with your password used to access the project database in pgAdmin4, and replace "IP_ADDRESS" with the IP address or hostname of the server where the PostgreSQL database is running.

To obtain your IP address, type either "ipconfig" for windows or "ifconfig" for mac in the terminal and obtain the series of numbers that corresponds to the "IPv4 Address" in the output.

In [207]:
#Import sqlalchemy
from sqlalchemy import create_engine

# Create the engine to interact with the SQL database. Replace 'PASSWORD' with the password your password.\
# and "IP_ADDRESS" with your IP address
engine = create_engine('postgresql://postgres:PASSWORD@IP_ADDRESS/FraudDetection')

# Load the dataframe into the SQL Database
fraud_df.to_sql('fraud_data', engine, index=False, if_exists='replace')

144